# Prelude

In [5]:
import numpy
import matplotlib
import seaborn
import pandas

from matplotlib import pyplot
seaborn.set()

In [6]:
cd ~/TP/connections

/home/mfixman/Dropbox/continuous/TP/connections

# Getting Data

In [22]:
nomodel = pandas.read_csv('results/NoModel.csv')
nomodel = nomodel.loc[lambda x: x.event.isna()].drop('event
nomodel

,event,problem,part,outcome,proved,seconds,mode,policy,seed,steps,proof_size,axioms,kept_axioms,prediction_seconds,guidance_fallback,parseable,error,problems,proved_seconds_total,proved_seconds_mean
0,NaN,/rds/user/msf43/hpc-work/TPTP/Problems/ALG/ALG...,9.0,DeclaredSatisfiable,false,43.437033,base,satresetcop,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,/rds/user/msf43/hpc-work/TPTP/Problems/ALG/ALG...,8.0,DeclaredSatisfiable,false,43.447103,base,satresetcop,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,/rds/user/msf43/hpc-work/TPTP/Problems/ALG/ALG...,9.0,DeclaredSatisfiable,false,0.010413,base,satresetcop,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,/rds/user/msf43/hpc-work/TPTP/Problems/ALG/ALG...,9.0,DeclaredSatisfiable,false,43.470687,base,satresetcop,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,/rds/user/msf43/hpc-work/TPTP/Problems/ALG/ALG...,8.0,DeclaredSatisfiable,false,0.042170,base,satresetcop,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3568,NaN,/rds/user/msf43/hpc-work/TPTP/Problems/TOP/TOP...,9.0,Timeout,false,120.005093,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3569,NaN,/rds/user/msf43/hpc-work/TPTP/Problems/TOP/TOP...,9.0,Timeout,false,120.000856,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3570,NaN,/rds/user/msf43/hpc-work/TPTP/Problems/TOP/TOP...,8.0,Timeout,false,120.001650,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3571,NaN,/rds/user/msf43/hpc-work/TPTP/Problems/TOP/TOP...,9.0,Timeout,false,120.001051,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3572,NaN,/rds/user/msf43/hpc-work/TPTP/Problems/TOP/TOP...,9.0,Timeout,false,120.000401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
nomodel.drop('event', axis = 1)

,problem,part,outcome,proved,seconds,mode,policy,seed,steps,proof_size,axioms,kept_axioms,prediction_seconds,guidance_fallback,parseable,error,problems,proved_seconds_total,proved_seconds_mean
0,/rds/user/msf43/hpc-work/TPTP/Problems/ALG/ALG...,9.0,DeclaredSatisfiable,false,43.437033,base,satresetcop,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,/rds/user/msf43/hpc-work/TPTP/Problems/ALG/ALG...,8.0,DeclaredSatisfiable,false,43.447103,base,satresetcop,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,/rds/user/msf43/hpc-work/TPTP/Problems/ALG/ALG...,9.0,DeclaredSatisfiable,false,0.010413,base,satresetcop,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,/rds/user/msf43/hpc-work/TPTP/Problems/ALG/ALG...,9.0,DeclaredSatisfiable,false,43.470687,base,satresetcop,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,/rds/user/msf43/hpc-work/TPTP/Problems/ALG/ALG...,8.0,DeclaredSatisfiable,false,0.042170,base,satresetcop,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3568,/rds/user/msf43/hpc-work/TPTP/Problems/TOP/TOP...,9.0,Timeout,false,120.005093,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3569,/rds/user/msf43/hpc-work/TPTP/Problems/TOP/TOP...,9.0,Timeout,false,120.000856,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3570,/rds/user/msf43/hpc-work/TPTP/Problems/TOP/TOP...,8.0,Timeout,false,120.001650,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3571,/rds/user/msf43/hpc-work/TPTP/Problems/TOP/TOP...,9.0,Timeout,false,120.001051,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3572,/rds/user/msf43/hpc-work/TPTP/Problems/TOP/TOP...,9.0,Timeout,false,120.000401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN